# Generated by Django 5.0.5 on 2024-05-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='category',
        ),
    ]
