# Generated by Django 5.0.5 on 2024-05-26 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('loans', '0002_remove_loan_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
